# Generated by Django 2.2.19 on 2021-09-27 05:35

from django.db import migrations, models
import enum


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210927_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(verbose_name=enum.unique),
        ),
    ]
